"""Initial migration

Revision ID: 13c31406bc39
Revises: 
Create Date: 2025-04-26 11:10:19.267592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c31406bc39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bucket_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'storage_bucket', ['bucket_id'], ['bucket_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_material', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('bucket_id')

    # ### end Alembic commands ###
